apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: PORT
              value: "{{ .Values.api.port }}"
            - name: DB
              value: "{{ .Values.api.db.name }}"
            - name: DBUSER
              value: "{{ .Values.api.db.user }}"
            - name: DBPASS
              value: "{{ .Values.api.db.password }}"
            - name: DBHOST
              value: "{{ .Values.api.db.host }}"
            - name: DBPORT
              value: "3306"