apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nonso-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: "alb-dev"
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=devops, ManagedBy=devopsengineersam, Site=jakshem

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/subnets: subnet-0078e7fc2985ae74d, subnet-086210ec55bfdea5d, subnet-0ab883e73c51ef044
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:533267037417:certificate/483743fd-14bf-4650-b08b-36c637ab32b4
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.hosts.host }}
      http:
        paths:
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: {{ .Values.web.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: {{ .Values.api.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: {{ .Values.app.port }}