web:
  image: 533267037417.dkr.ecr.us-east-1.amazonaws.com/toptal-app
  tag: v1.0.0
  port: 3000
  replicaCount: 2

api:
  image: 533267037417.dkr.ecr.us-east-1.amazonaws.com/toptal-api
  tag: v1.0.0
  port: 4000
  replicaCount: 2
  db:
    host: nonso-db.cr28qg4sq75y.us-east-1.rds.amazonaws.com
    name: catalog
    user: admin
    password: yourpassword

app:
  image: 533267037417.dkr.ecr.us-east-1.amazonaws.com/construction
  tag: v1.1.6
  pullPolicy: IfNotPresent
  replicaCount: 2

ingress:
  enabled: true
  hosts:
    host: app-assess.chebsam.people.aws.dev
  annotations:
    alb.ingress.kubernetes.io/group.name: "alb-dev"
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=devops,ManagedBy=devopsengineersam,Site=jakshem
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-0078e7fc2985ae74d,subnet-086210ec55bfdea5d,subnet-0ab883e73c51ef044
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:533267037417:certificate/483743fd-14bf-4650-b08b-36c637ab32b4