web:
  image: 533267037417.dkr.ecr.us-east-1.amazonaws.com/toptal-app
  tag: latest
  port: 3000
  replicaCount: 2

api:
  image: 533267037417.dkr.ecr.us-east-1.amazonaws.com/toptal-api
  tag: latest
  port: 4000
  replicaCount: 2
  db:
    host: nonso-db.cr28qg4sq75y.us-east-1.rds.amazonaws.com # Replace with your RDS endpoint
    name: mydatabase
    user: admin
    password: yourpassword

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  hosts:
    - host: app-assess.chebsam.people.aws.dev # Replace with your domain
      paths:
        - /web
        - /api