version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalog
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  api:
    build: ./api
    container_name: node_api
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: catalog
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app-network

  web:
    build: ./web
    container_name: node_web
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge