name: Deploy Infrastructure

on:
  push:
    branches:
      - infra # Monitor changes in the infra branch only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Use the desired Terraform version

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra # Path to your Terraform directory

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra