name: Deploy infra/eks-rds infrastructure

on:
  push:
    branches:
      - infra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/eks-rds

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra/eks-rds

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra/eks-rds

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra/eks-rds