name: Deploy infra/eks-rdsstructure

on:
  push:
    branches:
      - infra/eks-rds # Monitor changes in the infra/eks-rds branch only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0 # Use the desired Terraform version

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/eks-rds # Path to your Terraform directory

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra/eks-rds

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra/eks-rds

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra/eks-rds